PRX/theworld.org

now.json
Closes #59
- Adds headers to routes, namely cache-control headers.
=> 59: Add headers to routes

.eslintrc.yml, contexts/AppContext.ts, interfaces/content/content.interface.ts, interfaces/page/page.interface.ts, lib/fetch/api/fetchApi.ts, lib/fetch/api/fetchPriApi.ts, lib/fetch/api/index.ts, lib/parse/audio/download.ts, package.json, pages/_app.tsx, pages/api/app.ts, pages/api/homepage.ts, pages/api/query/alias/[...slugs].ts, pages/api/story/[id].ts, pages/index.tsx, yarn.lock
Closes #77 
- Adds proxy API endpoints so browser doesn't communicate with remote API directly and receive cookies from API server.
>  ...or...
>  ...then...
=> 75: api proxy endpoints

components/Bio/Bio.tsx, components/Category/Category.tsx, components/ResourceComponentMap.ts, components/Sidebar/SidebarEpisode/SidebarEpisode.tsx, components/Story/layouts/default/Story.default.tsx, components/StoryCard/StoryCard.tsx, components/StoryCardGrid/StoryCardGrid.tsx, components/Tags/Tags.styles.ts, components/Term/Term.tsx, components/Term/index.ts, lib/fetch/api/fetchApi.ts, pages/api/term/[id]/index.ts, pages/api/term/[id]/stories/[page].ts
Closes #32 
- Adds pages for Terms (tags, open calais fields, etc.)
> ...or...
> ...then...
=> #32: Term pages

components/StoryCard/StoryCard.styles.ts, components/StoryCard/StoryCard.tsx, components/pages/Story/layouts/default/components/StoryLede/StoryLede.default.tsx
- default story layout renders w/o error
- story card looks better
Closes #130 
- Default story views should no longer fatal error when image is missing.
- Story card layout should look better when an image is missing.
> ...or...
> ...then...
=> #130: Handle missing story image

components/AppLoadingBar/AppLoadingBar.tsx, components/pages/Bio/Bio.tsx, components/pages/ResourceComponentMap.ts, components/pages/Team/Team.styles.ts, components/pages/Team/Team.tsx, components/pages/Team/components/TeamHeader/TeamHeader.styles.ts, components/pages/Team/components/TeamHeader/TeamHeader.tsx, components/pages/Team/components/TeamHeader/index.ts, components/pages/Team/components/index.ts, components/pages/Team/index.ts, lib/fetch/api/fetchApi.ts, pages/_app.tsx, pages/api/team.ts, pages/index.tsx, store/actions/fetchTeamData.ts, store/actions/index.ts, vercel.json
Closes #98 
- add team page component and routing
- refactor alias handling to handle internal aliases
- ensure app scrolls to top when content type/id changes
> ...or...
> ...then...
=> #98: Add Team Page

interfaces/content/content.interface.ts, pages/index.tsx
Closes #132 
- Adds logic to do redirect to external URL returned from alias look up query.
> ...then...
> ...then...
=> #132: Handle external redirects for aliases

components/Sidebar/SidebarLatestStories/SidebarLatestStories.styles.ts, components/Sidebar/SidebarLatestStories/SidebarLatestStories.tsx, components/Sidebar/SidebarLatestStories/index.ts, components/Sidebar/index.ts, components/pages/Bio/Bio.tsx, components/pages/Category/Category.tsx, components/pages/Episode/Episode.tsx, components/pages/Homepage/Homepage.tsx, components/pages/Program/Program.tsx, components/pages/Story/layouts/default/Story.default.tsx, components/pages/Term/Term.tsx
Closes #135
- moves latest stories list card tp its own component
- update pages w/ sidebar to use new latest stories component
> ...or...
> ...then...
=> #135: Add component for sidebar latest stories

components/HtmlContent/HtmlContent.tsx, components/pages/Newsletter/Newsletter.tsx, pages/api/newsletter/[id].ts, store/actions/fetchNewsletterData.ts, store/actions/index.ts
Closes #138 
- Fixes newsletter data fetching so pages should load once again.
> ...or...
> ...then...
> DO NOT MERGE until PublicRadioInternational/pri.org#1506 is deployed.
=> #138: Update newsletter data fetch pattern

pages/_document.tsx
Closes #155 
- Adds language metatag to the head
> ...or...
> ...then...
=> #155 add lang

components/AppFooter/AppFooter.styles.ts, components/AppFooter/AppFooter.tsx, components/AppHeader/AppHeader.tsx
Closes #158
Closes #152 
Since these are mostly fixes to the same file:
- Adds height and width to sponsor names
- Adds discernible text to links containing only SVGs/images (logos in header/footer)
- Footer links to have min-height and width, tappable at least 48x48.
> ...or...
> ...then...
=> #152/#158 Accessible Footer

.gitignore, @types/index.d.ts, lib/fetch/api/fetchApi.ts, lib/routing/content.ts, lib/routing/handleButtonClick.spec.ts, lib/routing/handleButtonClick.ts, package.json, pages/_app.tsx, pages/api/query/alias/[...slugs].ts, pages/index.tsx, pages/render/[...alias].tsx, store/actions/fetchAppData.ts, store/configureStore.ts, vercel.json, yarn.lock
Closes #144 
- Refactors vercel config to use non-legacy configuration props.
- Adds a `render/[...alias]` catch-all page.
- Refactors app and redux initialization.
> ...or...
> ...then...
=> #144: Update Vercel config to used `headers` and `rewrites`

package.json, pages/_document.tsx, vercel.json, yarn.lock
Closes #157 
- defers initial webfont load
> ...or...
> ...then...
=> 157 Defer webfont load

components/Tags/Tags.styles.ts, components/Tags/Tags.tsx, components/pages/Story/layouts/feature/components/StoryHeader/StoryHeader.feature.tsx
Closes #147 
- The tags and categories list at the end of stories didn't have appropriate sizing (48x48) so I redesigned them a bit here. 
> ...or...
> ...then...
=> #147: restyle story tags list

components/AppHeader/DrawerSocialNav/DrawerSocialNav.tsx, components/AudioPlayer/AudioPlayer.tsx
Closes #148 
- Any links that have the `target=_blank` attribute need to have `rel="noopener noreferrer"` set as well
> ...or...
> ...then...
=> #148 adds noopener and noreferrer attributes to external links

components/Tags/Tags.styles.ts, components/Tags/Tags.tsx, components/pages/Story/layouts/feature/components/StoryHeader/StoryHeader.feature.styles.ts, components/pages/Story/layouts/feature/components/StoryHeader/StoryHeader.feature.tsx
Closes #154
- Updates the teaser on feature story pages to a `<p>` tag. I don't think the teaser works as an h2 of the page. 
- Updates the category/tags label to an H2.
- Restyles both
> ...or...
> ...then...
=> #154 fixes sequential headers and styling

.editorconfig, components/AppFooter/AppFooter.tsx, components/CtaRegion/components/CtaMessageNewsletter/CtaMessageNewsletter.styles.ts, lib/parse/menu/parseMenu.ts
This is a PR that applies fixes from #166 to get them in use while the modal work is on hold.
- Fixes parsing of `referrerpolicy` menu item attribute so it is applied to react anchor camelcased.
- Fixes theme override of newsletter CTA form labels.
- Adds `.editorconfig` file.
- Various prettier formatting changes.
> ...or...
> ...then...
=> HOTFIX: Apply bug fixes from #166 PR

components/NewsletterForm/NewsletterForm.tsx
- Subscribe now implies paid. Updates Newsletter form label to say "sign up"
> ...or...
> ...then...
=> HOTFIX: update newsletter button label

components/pages/Newsletter/Newsletter.tsx, lib/fetch/index.ts, lib/fetch/newsletter/fetchNewsletter.ts, lib/fetch/newsletter/index.ts, store/actions/fetchNewsletterData.ts
Closes #190 
- Converts data fetch action to use static SSR friendly function.
> ...or...
> ...then...
=> 190: Convert data fetch for static SSR

components/pages/Story/layouts/default/styles/body/Story.body.typography.ts, components/pages/Story/layouts/feature/styles/body/Story.body.typography.ts
Closes #195
- Prevents styling of anchor tags within Mui components in stories' body content.
> ...or...
> ...then...
=> Fix text colors of body CTA buttons on mobile

components/AppCtaBanner/AppCtaBanner.tsx, components/AppCtaLoadUnder/AppCtaLoadUnder.tsx, components/pages/Audio/Audio.tsx, components/pages/Bio/Bio.tsx, components/pages/Category/Category.tsx, components/pages/Episode/Episode.tsx, components/pages/Homepage/Homepage.tsx, components/pages/Program/Program.tsx, components/pages/Story/Story.tsx, components/pages/Story/layouts/default/Story.default.tsx, interfaces/state/ctaData.interface.ts, interfaces/state/pageState.interface.ts, interfaces/state/ui.interface.ts, pages/_app.tsx, pages/render/[...alias].tsx, store/actions/fetchCtaData.ts, store/actions/fetchHomepageData.ts, store/actions/fetchStoryData.ts, store/reducers/ctaData.ts, store/reducers/index.ts
Closes #189 
- Re-adds app banner and load under CTA messaging
> ...or...
> ...then...
=> #189: App CTA banner data

components/Sidebar/SidebarList/SidebarList.tsx, components/Tags/Tags.styles.ts, components/Tags/Tags.tsx, store/reducers/ctaData.ts
Closes #170 
- adds `<li>` wrappers to link list items
- some doc corrections
- remove console.log
> ...or...
> ...then...
=> #170: Wrap link list button with `<li>`

components/NewsletterForm/NewsletterForm.tsx, components/StoryCardGrid/StoryCardGrid.tsx
- I noticed that image progress loading bars were missing an aria-label in story cards. Lighthouse caught it. `aria-label="Progress Bar"` is needed on all progress bars. 
> ...or...
> ...then...
=> HOTFIX: Adds aria-label to progress bars
